### ISSUE TITLE
Await for Database start

### ISSUE THREAD

**Issue by iradio** [adn-tm/jsonschemaregistry#1]
Current beheiviour:
registry fails on stuartup usin docker-compose with error:
```
Database warm up error Error: connect ECONNREFUSED 172.19.0.10:8123
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.19.0.10',
  port: 8123
}
```
docker-compose config runs registry after ClickHouse, but CH needs some time to start up.
```
  registry:
    image: bitnami/node:12
    hostname: registry
    depends_on:
      - clickhouse

```
Solution: Await for CH start up.
